version: '3.9'
services:
  stexs-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Adminxyz123!
    ports:
      - "1433:1433"
  stexs-backend:
    build: 
      context: ./backend
    ports:
      - "5000:80"
    expose:
      - "80"
    restart: on-failure
    depends_on:
      - stexs-db
    environment:
      - DontBuildSwagger=true
      - ASPNETCORE_ENVIRONMENT=Development
  stexs-frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - stexs-backend