name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build FE Docker Image
      run: docker build ./frontend --tag stexs-frontend
    - name: Build BE Docker Image
      run:  docker build ./backend --tag stexs-backend
      
    - name: login to ghcr
      run: echo "${{ env.GHCR-PAT }}" | docker login ghcr.io -u niposch --password-stdin
    - name: Publish to GHCR
      run: docker push ghcr.io/niposch/STExS/stexs-frontend:latest; docker push ghcr.io/niposch/STExS/stexs-backend:latest
